nodeLinker: node-modules

npmScopes:
  wizehire:
    npmAuthToken: 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
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
