nodeLinker: node-modules

npmScopes:
  wizehire:
    npmAuthToken: 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
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
